### ISSUE TITLE
Android App Rating - PostponableAction not found

### ISSUE THREAD

**Issue by JaviTeamCMP** [Leanplum/Leanplum-Android-SDK#527]
## Expected Behavior
Android App Rating should work for all SDK versions

## Actual Behavior
We have implemented the AppRating for Android by following the documentation: https://docs.leanplum.com/docs/app-review-request#android-review-request-setup but after upgrade from `5.7.0` to `7.0.0`, the class implemented is failing as `com.leanplum.callbacks.PostponableAction` no longer exists from the `6.0.0` version. 

## Steps to Reproduce the Problem

  1. Use the SDK 7.0.0 version `implementation "com.leanplum:leanplum-fcm:7.0.0"`
  1. Follow the [documentation](https://docs.leanplum.com/docs/app-review-request#android-review-request-setup ) to create the `AppRating.java` class for android
  1. Build the project

## Specifications

  - Version: 7.0.0
  - Platform: Android
  - Subsystem: Capacitor

**Comment by hborisoff** [comment]
@JaviTeamCMP 
You need to do a migration on the templates, because we refactored them in 6.0.0.
If you haven't, please follow our migration guides - [6.0.0](https://docs.leanplum.com/changelog/custom-in-app-templates-migration-android-600), [7.0.0](https://docs.leanplum.com/changelog/android-sdk-700-and-ios-sdk-600).
The [AppRating template](https://github.com/Leanplum/Leanplum-Android-CustomTemplates/blob/main/app/src/main/java/com/leanplum/customtemplates/AppRating.java) is added in our custom templates repository and already migrated to 6.0.0.

**Comment by JaviTeamCMP** [comment]
All good now, thanks!
